In [27]:
import numpy as np
import pandas as pd

In [77]:
subs = pd.read_csv('/content/subs.csv').squeeze()
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [35]:
ks = pd.read_csv('/content/kohli_ipl.csv', index_col= 'match_no').squeeze()

ks

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [83]:
movies = pd.read_csv('/content/bollywood.csv', index_col= 'movie').squeeze()

movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [45]:
ks.size

215

In [46]:
subs.size

1500

In [47]:
ks.shape

(215,)

In [49]:
ks.dtype

dtype('int64')

In [50]:
subs.dtype

dtype('O')

In [52]:
subs.value_counts(ascending = False)

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [54]:
ks.value_counts(ascending = False)

runs
0     9
1     8
12    8
9     7
8     6
     ..
46    1
29    1
84    1
90    1
53    1
Name: count, Length: 78, dtype: int64

In [55]:
ks.name

'runs'

In [56]:
ks.is_unique

False

In [57]:
ks.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       206, 207, 208, 209, 210, 211, 212, 213, 214, 215],
      dtype='int64', name='match_no', length=215)

In [58]:
ks.values

array([  1,  23,  13,  12,   1,   9,  34,   0,  21,   3,  10,  38,   3,
        11,  50,   2,  22,  19,  16,  15,  20,  38,  19,  24,   7,   2,
        16,  17,  24,  38,  34,  42,  13,  58,   3,  14,  37,   9,  23,
        12,  71,  35,  30,  56,  67,  27,  27,  39,  15,  11,  31,  70,
         8,  35,   8,   6,  57,  22,  16,   4,  16,  18,  45,   9,  36,
         9,   3,  73,  42,  24,  51,  35,  58,  65,   1,  11,   1,  32,
        25,  57,  93,  99,  17,  14,  56,  49,   0,  31,  21,   4,   0,
        35,   0,   4,  10,  27,  67,  38,  73,  13,  41,  18,  51,  62,
        35,   1,  34,  48,  32,  82,  19,  44,   1,  12,  12,  75,  79,
        33,  80, 100,  14,  52, 108,  20,   7, 109,  75, 113,  54,   0,
        54,  62,  28,  64,   0,  10,  55,  20,   6,   5,  58,  31,  21,
        57,  92,  30,  18,  68,  32,   8,  39,  70,  48,  12,   4,   6,
        46,   3,  23,  84,  41,  67,   8, 100,   9,  13,  23,  25,  16,
        18,   9,   7,  29,   1,  72,  43,  43,  90,  48,  14,  33,  50,
         8,   6,  33,  33,   5,  72,   8,  12,  35,   5,  25,   5,   4,
        25,  51,  53,  39,  41,  12,   5,  48,   1,  12,   0,   0,   9,
        58,  30,   0,  20,  73,  25,   7])

In [65]:
print(ks.sort_values(ascending=False).head(1).values[0])

113

In [73]:
ks.sample(5)

match_no
170    18
186    33
131    54
32     42
59     16
Name: runs, dtype: int64

In [82]:
print(subs.mean())

print(ks.mean())

print(ks.median())

135.64383561643837
30.855813953488372
24.0

In [86]:
print(movies.mode())

0    Akshay Kumar
Name: lead, dtype: object

In [89]:
movies.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [90]:
ks.mode()

0    0
Name: runs, dtype: int64

In [93]:
ks[6]

np.int64(9)

In [106]:
movies.index

Index(['Uri: The Surgical Strike', 'Battalion 609',
       'The Accidental Prime Minister (film)', 'Why Cheat India',
       'Evening Shadows', 'Soni (film)', 'Fraud Saiyaan', 'Bombairiya',
       'Manikarnika: The Queen of Jhansi', 'Thackeray (film)',
       ...
       'Raaz (2002 film)', 'Zameen (2003 film)', 'Waisa Bhi Hota Hai Part II',
       'Devdas (2002 Hindi film)', 'Kaante', 'Hum Tumhare Hain Sanam',
       'Aankhen (2002 film)', 'Saathiya (film)', 'Company (film)',
       'Awara Paagal Deewana'],
      dtype='object', name='movie', length=1500)

In [109]:
# integers
runs = [13,24,56,78,100]

runs_ser = pd.Series(runs)

In [110]:
runs_ser

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [112]:
runs_ser[2:4] = 100

In [113]:
runs_ser

0     13
1     24
2    100
3    100
4    100
dtype: int64

In [118]:
runs_ser[100] = 70

runs_ser

0       13
1       24
2      100
3      100
4      100
5       30
100     70
dtype: int64

# **SERIES PRACTICE QUESTIONS**

In [121]:
import pandas as pd

# Load the Kaggle Pokemon dataset directly into a DataFrame
url = "https://githubusercontent.com"
# Let's use a cleaner direct URL for immediate practice (Marvel Comic Characters)
df = pd.read_csv("https://githubusercontent.com")

# Create a clean Series for our exercises (Passenger Names indexed by Ticket Number)
char_series = df.set_index('Ticket')['Name'].squeeze("columns")
# Create a numerical Series (Ticket Fare indexed by Passenger Name)
fare_series = df.set_index('Name')['Fare'].squeeze("columns")

URLError: <urlopen error [Errno -5] No address associated with hostname>

In [123]:
!kaggle datasets download -d kartikkadian/pokemondata

Dataset URL: https://www.kaggle.com/datasets/kartikkadian/pokemondata
License(s): unknown
Downloading pokemondata.zip to /content
100% 46.6k/46.6k [00:00<00:00, 1.18MB/s]

In [124]:
# 2. Download hui zip file ko unzip karein
!unzip pokemondata.zip

# 3. Faltu zip file ko delete karein (optional)
!rm pokemondata.zip

Archive:  pokemondata.zip
  inflating: pokemon.csv

In [128]:
import pandas as pd

# Load your dataset
df = pd.read_csv('/content/pokemon.csv')
df

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

In [129]:
# Detect column names (handling case sensitivity)
type_col = 'Type 1' if 'Type 1' in df.columns else 'type1'
name_col = 'Name' if 'Name' in df.columns else 'name'
speed_col = 'Speed' if 'Speed' in df.columns else 'speed'

# FIX: Removed .squeeze("columns") because selecting a single column
# from df.set_index() already returns a clean Series.
poke_types = df.set_index(type_col)[name_col]
poke_speed = df.set_index(name_col)[speed_col]

In [131]:
poke_speed

name
Bulbasaur      45
Ivysaur        60
Venusaur       80
Charmander     65
Charmeleon     80
             ...
Celesteela     61
Kartana       109
Guzzlord       43
Necrozma       79
Magearna       65
Name: speed, Length: 801, dtype: int64

# **# Challenge 1: The Speed Demon (Filtering & Indexing)**
Dataset: `poke_speed`
### **Task:**
1.   Find the average speed of all Pokémon.
2.   Filter the Series to find all Pokémon that are at least twice as fast as the average speed.
3.   Sort these fast Pokémon in descending order and return just the top 5 fastest names.

In [132]:
print(poke_speed.mean())

66.33458177278402

In [137]:
print(poke_speed[poke_speed >= 2*(poke_speed.mean())])

name
Beedrill      145
Alakazam      150
Electrode     150
Aerodactyl    150
Mewtwo        140
Sceptile      145
Ninjask       160
Manectric     135
Deoxys        180
Lopunny       135
Accelgor      145
Pheromosa     151
Name: speed, dtype: int64

In [138]:
print(poke_speed[poke_speed >= 2*(poke_speed.mean())].sort_values(ascending=False).head(5))

name
Deoxys       180
Ninjask      160
Pheromosa    151
Alakazam     150
Electrode    150
Name: speed, dtype: int64

## Challenge 2: Type Dominance (Value Counting & String Matching)

**Dataset:** `poke_types`  
**Tasks:**
1. Find the top 3 most common primary Pokémon types using your Series.
2. Filter your Series to find all Pokémon whose names start with the letter "M" and belong to the "Water" or "Fire" type.

*Hint: You will need to check both the index values and the Series values.*

In [139]:
poke_types

type1
grass       Bulbasaur
grass         Ivysaur
grass        Venusaur
fire       Charmander
fire       Charmeleon
              ...
steel      Celesteela
grass         Kartana
dark         Guzzlord
psychic      Necrozma
steel        Magearna
Name: name, Length: 801, dtype: object

In [154]:
poke_types.index.value_counts().head(3)

type1
water     114
normal    105
grass      78
Name: count, dtype: int64

In [145]:
poke_types.is_unique

True

In [166]:
poke_types[poke_types.str.startswith('M') & poke_types.index.isin(['water', 'fire'])]

type1
fire        Magmar
water     Magikarp
fire       Moltres
water       Marill
fire      Magcargo
water      Mantine
fire         Magby
water       Mudkip
water    Marshtomp
water      Milotic
fire      Monferno
water      Mantyke
fire     Magmortar
water      Manaphy
Name: name, dtype: object

## Challenge 3: Advanced Binning & Analysis

**Dataset:** `poke_speed`  
**Tasks:**
1. Group the Pokémon speeds into 3 distinct categories: "Slow", "Medium", and "Fast" using `pd.cut()`.
2. Convert this new Series into a categorical type.
3. Calculate the exact percentage of Pokémon that fall into the "Slow" category.

In [167]:
poke_speed

name
Bulbasaur      45
Ivysaur        60
Venusaur       80
Charmander     65
Charmeleon     80
             ...
Celesteela     61
Kartana       109
Guzzlord       43
Necrozma       79
Magearna       65
Name: speed, Length: 801, dtype: int64

In [169]:
speed = pd.cut(poke_speed, bins=3, labels=['Slow', 'Medium', 'Fast'])

speed

name
Bulbasaur       Slow
Ivysaur         Slow
Venusaur      Medium
Charmander    Medium
Charmeleon    Medium
               ...
Celesteela      Slow
Kartana       Medium
Guzzlord        Slow
Necrozma      Medium
Magearna      Medium
Name: speed, Length: 801, dtype: category
Categories (3, object): ['Slow' < 'Medium' < 'Fast']

In [173]:
speed.value_counts(normalize=True)

speed
Slow      0.490637
Medium    0.478152
Fast      0.031211
Name: proportion, dtype: float64

In [191]:
a = speed.value_counts()[0]

b = speed.value_counts().sum()

c = a/b*100

print(round(c,2))

49.06

/tmp/ipykernel_3789/50174273.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  a = speed.value_counts()[0]

In [194]:
print(speed.value_counts(normalize=True)[0] * 100)

49.063670411985015

/tmp/ipykernel_3789/3524255827.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(speed.value_counts(normalize=True)[0] * 100)